services:
  - type: web
    name: book-platform-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: PORT
        value: 8000
      - key: FROM_EMAIL
        value: meesama89434@gmail.com
      - key: FROM_NAME
        value: Book Platform 