"""add_cv_applications_table

Revision ID: 83b3bde156fe
Revises: e08d68b41ef7
Create Date: 2025-09-04 10:27:21.241787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83b3bde156fe'
down_revision = 'e08d68b41ef7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 