"""add is_blocked column to books

Revision ID: 9b0c5debad42
Revises: 83b3bde156fe
Create Date: 2025-09-05 16:24:53.646808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b0c5debad42'
down_revision = '83b3bde156fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('is_blocked', sa.Boolean(), nullable=True))
    op.add_column('books', sa.Column('blocked_reason', sa.Text(), nullable=True))
    op.add_column('books', sa.Column('blocked_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'blocked_at')
    op.drop_column('books', 'blocked_reason')
    op.drop_column('books', 'is_blocked')
    # ### end Alembic commands ### 