"""add_is_featured_writer_column_to_users

Revision ID: de3f86a7cc8f
Revises: f1d416a72ff6
Create Date: 2025-09-02 20:39:15.046430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de3f86a7cc8f'
down_revision = 'f1d416a72ff6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 