"""Add author_name field to Book model

Revision ID: f1d416a72ff6
Revises: 7d1c55a36584
Create Date: 2025-07-26 15:46:50.832789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1d416a72ff6'
down_revision = '7d1c55a36584'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'author_name')
    # ### end Alembic commands ### 